[package]
name = "satty"
version = "0.2.0"
edition = "2021"
authors = ["Matthias Gabriel <gabm+aur@mailbox.org>"]
description = "A screenshot annotation tool inspired by Swappy and Flameshot"
homepage ="https://github.com/gabm/satty"
repository ="https://github.com/gabm/satty"
license = "MPL-2.0"


[dependencies]
relm4 = { version = "0.6.2", features = ["macros", "libadwaita"] }
relm4-icons = { version = "0.6.0", features = ["number-circle-1-regular", "drop-regular", "arrow-redo-filled", "arrow-undo-filled", "save-regular", "copy-regular", "text-case-title-regular","text-font-regular","minus-large", "checkbox-unchecked-regular", "crop-filled", "arrow-up-right-filled", "rectangle-landscape-regular"] }
pangocairo = "0.17.10"
tokio = { version = "1.32.0", features = ["full"]}
gdk-pixbuf = "0.17.2"

# error handling
anyhow = "1.0"

# command line
clap = { version = "4.4.4", features = ["derive"] }
swayipc = { git = "https://github.com/JayceFayne/swayipc-rs.git", branch = "master" }
libwayshot = "0.2.0"

lazy_static = "1.4.0"
